global_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before: 5.0
  publish_frequency: 0.5 #before 0.5 1.0 1.5 2 2.5
  static_map: true
  transform_tolerance: 0.5 #chng0.5
  cost_scaling_factor: 10 #15
  inflation_radius: 0.5 #0.55