local_costmap:
  global_frame: map
  robot_base_frame: ebot_base
  update_frequency: 5.0 #before 5.0 1
  publish_frequency: 5.0 #before 2.0 2 2.5 3.5
  static_map: false
  rolling_window: true
  width: 5 #2.5 
  height: 5 #2.5 
  resolution: 0.050 #increase to for higher res 0.025 chng
  transform_tolerance: 0.5 #chng0.5
  cost_scaling_factor: 10 #5 1.0
  inflation_radius: 0.5 #0.55 0.8