TrajectoryPlannerROS:
  max_vel_x: 0.5 #chng 0.5
  min_vel_x: 0.005
  max_vel_theta: 20 #1
  min_vel_theta: -5
  min_in_place_vel_theta: 2.0 #0.4
  acc_lim_theta: 30.0 #3.2
  acc_lim_x: 2.5
  acc_lim_y: 2.5
  holonomic_robot: false
  sim_time: 1.5
  controller_frequency: 10